-- AlterTable
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "routeGeometry" JSONB;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "routeDurationSeconds" INTEGER;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "riderLat" DOUBLE PRECISION;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "riderLng" DOUBLE PRECISION;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "riderLocationAt" TIMESTAMP(3);
