-- AlterTable
ALTER TABLE "Order" ADD COLUMN "senderName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN "senderPhone" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN "receiverName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN "receiverPhone" TEXT NOT NULL DEFAULT '';
